### ISSUE TITLE
When building I receive this error

### ISSUE THREAD

**Issue by officialmelon** [imbushuo/NintendoSwitchPkg#20]
Use GCC at /opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-elf/bin/aarch64-elf- to run builds.
Stamp build.
Build NintendoSwitchPkg for NintendoSwitch (DEBUG).
Build environment: Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-20.04-focal
Build start time: 13:44:53, Feb.12 2022

WORKSPACE        = /home/root1/edk2
EDK_TOOLS_PATH   = /home/root1/edk2/BaseTools
CONF_PATH        = /home/root1/edk2/Conf

Architecture(s)  = AARCH64

Processing meta-data .Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /home/root1/edk2/NintendoSwitchPkg/NintendoSwitch.dsc
.

build.py...
/home/root1/edk2/NintendoSwitchPkg/NintendoSwitch.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found
        in [/home/root1/edk2/ArmPlatformPkg/PrePi/PeiUniCore.inf] [AARCH64]
        consumed by module [/home/root1/edk2/ArmPlatformPkg/PrePi/PeiUniCore.inf]

- Failed -
Build end time: 13:44:55, Feb.12 2022
Build total time: 00:00:02

Write-Error: Build target NintendoSwitch failed.
False

**Comment by officialmelon** [comment]
Any help would be appreciated

**Comment by officialmelon** [comment]
Ok i fixed the error but now i have a new error I'm using WSL ubuntu 20.04:
 : error C0DE: Unknown fatal error when processing [/home/root1/edk2/MdeModulePkg/MdeModulePkg.dec]

(Please send email to devel@edk2.groups.io for help, attaching following call stack trace!)

(Python 2.7.18 on linux2) Traceback (most recent call last):
  File "/home/root1/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 2695, in Main
    MyBuild.Launch()
  File "/home/root1/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 2490, in Launch
    self._MultiThreadBuildPlatform()
  File "/home/root1/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 2282, in _MultiThreadBuildPlatform
    Wa, self.BuildModules = self.PerformAutoGen(BuildTarget,ToolChain)
  File "/home/root1/edk2/BaseTools/BinWrappers/PosixLike/../../Source/Python/build/build.py", line 2148, in PerformAutoGen
    self.Progress
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py", line 43, in __init__
    self._InitWorker(Workspace, MetaFile, Target, Toolchain, Arch, *args, **kwargs)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py", line 120, in _InitWorker
    self.CollectAllPcds()
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py", line 495, in CollectAllPcds
    Pa.CollectFixedAtBuildPcds()
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/PlatformAutoGen.py", line 212, in CollectFixedAtBuildPcds
    for LibAuto in self.LibraryAutoGenList:
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/PlatformAutoGen.py", line 1139, in LibraryAutoGenList
    for La in Ma.LibraryAutoGenList:
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 1882, in LibraryAutoGenList
    for Lib in La.CodaTargetList:
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 952, in CodaTargetList
    self.Targets
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 938, in Targets
    self.SourceFileList
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 759, in SourceFileList
    if F.Dir not in self.IncludePathList:
  File "/home/root1/edk2/BaseTools/Source/Python/Common/caching.py", line 28, in __get__
    Value = obj.__dict__[self._function.__name__] = self._function(obj)
  File "/home/root1/edk2/BaseTools/Source/Python/AutoGen/ModuleAutoGen.py", line 1127, in IncludePathList
    IncludesList = Package.Includes
  File "/home/root1/edk2/BaseTools/Source/Python/Workspace/DecBuildData.py", line 287, in Includes
    ErrorCode, ErrorInfo = File.Validate()
  File "/home/root1/edk2/BaseTools/Source/Python/Common/Misc.py", line 1573, in Validate
    RealFile, RealRoot = RealPath2(self.File, self.Root, self.AlterRoot)
  File "/home/root1/edk2/BaseTools/Source/Python/Common/Misc.py", line 1552, in RealPath2
    NewFile = GlobalData.gAllFiles[os.path.normpath(os.path.join(Dir, File))]
  File "/home/root1/edk2/BaseTools/Source/Python/Common/Misc.py", line 640, in __getitem__
    for F in os.listdir(ParentDir):
  File "/home/root1/edk2/BaseTools/Source/Python/Common/LongFilePathOs.py", line 58, in listdir
    uList = os.listdir(u"%s" % LongFilePath(path))
OSError: [Errno 13] Permission denied: 'MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/c'


- Failed -

**Comment by officialmelon** [comment]
This is from when i was a noob... lol
